Feat/26
geneaky/BookChat pull request #47
Opened 2022-05-08 15:05 UTC by geneaky

#26 

카카오 책 검색 api를 호출하는 controller servicce test 작성을 통한 기능 구현

2022-05-08 23:52 UTC, Kova700 requested changes
publisher is not exist in BookDTO

2022-05-08 23:52 UTC, Kova700 commented on back/src/main/java/toy/bookchat/bookchat/domain/book/dto/BookDto.java
> +
I think publishers should also be added to the DTO.

2022-05-08 23:52 UTC, Kova700 commented on back/src/main/java/toy/bookchat/bookchat/domain/book/dto/BookSearchRequestDto.java
> +    private String author;
I think publishers should also be added to the DTO.

2022-05-08 23:52 UTC, Kova700 commented on back/src/main/java/toy/bookchat/bookchat/domain/book/dto/KakaoBook.java
> +                    .isbn(document.getIsbn())
I think publishers should also be added to the DTO.

2022-05-08 23:52 UTC, Kova700 commented on back/src/test/java/toy/bookchat/bookchat/domain/book/api/BookControllerTest.java
> +            .isbn(isbn)
I think publishers should also be added to the DTO.

2022-05-08 23:52 UTC, Kova700 commented on back/src/test/java/toy/bookchat/bookchat/domain/book/api/BookControllerTest.java
> +        bookDtos.add(getBookDto("213123", "effectiveJava", List.of("Joshua")));
I think publishers should also be added to the DTO.

2022-05-08 23:52 UTC, Kova700 commented on back/src/test/java/toy/bookchat/bookchat/domain/book/api/BookControllerTest.java
> +        bookDtos.add(getBookDto("213123", "effectiveJava", List.of("Joshua")));
I think publishers should also be added to the DTO.

2022-05-08 23:52 UTC, Kova700 commented on back/src/test/java/toy/bookchat/bookchat/domain/book/api/BookControllerTest.java
> +        bookDtos.add(getBookDto("213123", "effectiveJava", List.of("Joshua")));
I think publishers should also be added to the DTO.

2022-05-08 23:52 UTC, Kova700 commented on back/src/test/java/toy/bookchat/bookchat/domain/book/api/BookControllerTest.java
> +        bookDtos.add(getBookDto("213123", "effectiveJava", List.of("Joshua")));
I think publishers should also be added to the DTO.

2022-05-08 23:52 UTC, Kova700 commented on back/src/test/java/toy/bookchat/bookchat/domain/book/service/BookSearchServiceTest.java
> +    private String isbn = "8996991341 9788996991342";
I think publishers should also be added to the DTO.

2022-05-09 03:29 UTC, geneaky commented on back/src/main/java/toy/bookchat/bookchat/domain/book/dto/BookSearchRequestDto.java
> +    private String author;
이부분은 검색 조건을 받는 dto로 출판사는 따로 추가하지 않았습니다

2022-05-09 04:26 UTC, Kova700 approved these changes
Good!

2022-05-09 04:26 UTC, Kova700 commented on back/src/main/java/toy/bookchat/bookchat/domain/book/dto/BookSearchRequestDto.java
> +    private String author;
네 확인했습니다.

2022-05-09 07:58 UTC, merged