Feat/55
geneaky/BookChat pull request #68
Opened 2022-07-05 13:31 UTC by geneaky

#56
#55 

읽은, 읽을, 읽고있는 도서 등록 api

2022-07-05 20:33 UTC, Kova700 commented on back/src/main/java/toy/bookchat/bookchat/domain/book/repository/BookRepository.java
> +    Optional<Book> findByIsbn(String isbn);
이거 혹시 findByAuthor빠진건가요?

2022-07-05 20:38 UTC, Kova700 commented on back/src/main/java/toy/bookchat/bookchat/domain/bookshelf/ReadingStatus.java
> +    READY,
Ready단계가 ♥단계인가요?
책 선반에 들어간 책 상태들은 
읽고 있는 책 (READING)
읽은 책 (READ는 형태가 똑같으니까 FINISH?)
♥ (WISH) 이렇게 구분되는 게 좋지 않을까요?

2022-07-05 20:46 UTC, Kova700 requested changes
혹시 수정해야 할 사항이라면 수정 부탁 드립니다!

2022-07-06 00:15 UTC, geneaky commented on back/src/main/java/toy/bookchat/bookchat/domain/bookshelf/ReadingStatus.java
> +    READY,
Ready 단계가 읽을 책 등록(하트?인지는 << 저도 이거 기억이 가물가물하네요 )
Reading이 읽고있는 책으로 등록
complete가 읽은 책으로 등록 인데

선반에 아직 읽지 않고 읽을 예정인 책을 꽂아 둔다고 생각을 했어요

ready를 wish로 바꾸는 것은 아주 좋은생각인 것 같습니다 왜 그 단어 생각을 못했지?

2022-07-06 00:21 UTC, geneaky commented on back/src/main/java/toy/bookchat/bookchat/domain/book/repository/BookRepository.java
> +    Optional<Book> findByIsbn(String isbn);
이거는 kakao 도서 검색후에 저희 서비스에 등록된 책을 찾을 때 사용하는 메서드입니다

저자명으로 검색하는 기능은 외부 api호출하는 쪽에 작성되어 있는데 추후에 저희 서비스에서 사용하게되면
(예를 들어 내 서재에서 작가명으로 검색하기 기능 추가같은 요구 사항이 생기면)
그때 findByAuthor를 추가할 예정입니다

2022-07-06 00:25 UTC, Kova700 commented on back/src/main/java/toy/bookchat/bookchat/domain/book/repository/BookRepository.java
> +    Optional<Book> findByIsbn(String isbn);
아 네 알겠습니다!
 : )

2022-07-06 00:27 UTC, Kova700 commented on back/src/main/java/toy/bookchat/bookchat/domain/bookshelf/ReadingStatus.java
> +    READY,
ㅋㅋㅋㅋㅋ 수정해주세요~~!

2022-07-06 03:49 UTC, Kova700 requested changes
수정될 내용이 맞다면 수정 부탁드립니다.

2022-07-06 03:49 UTC, Kova700 commented on back/src/test/java/toy/bookchat/bookchat/domain/bookshelf/api/BookShelfControllerTest.java
> +                    fieldWithPath("readingStatus").description("READY"))));
READY .. 콜록콜록..

2022-07-06 03:54 UTC, geneaky commented on back/src/test/java/toy/bookchat/bookchat/domain/bookshelf/api/BookShelfControllerTest.java
> +                    fieldWithPath("readingStatus").description("READY"))));
크흠,,죄송합니다

2022-07-06 03:55 UTC, Kova700 approved these changes

2022-07-06 03:55 UTC, merged